version: '3.9'

services:
  stats-db:
    image: postgres:16.1
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      POSTGRES_DB: statsdb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "root", "-d", "statsdb"]
      interval: 5s
      timeout: 5s
      retries: 10

  stats-server:
    build:
      context: ./ewm-stats-service/stats-server
      dockerfile: Dockerfile
    container_name: stats-server
    ports:
      - "0.0.0.0:9090:9090"
    depends_on:
      stats-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/statsdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SERVER_PORT: 9090
      SERVER_ADDRESS: 0.0.0.0
      # Добавляем debug переменные
      SPRING_PROFILES_ACTIVE: debug
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK: DEBUG
      LOGGING_LEVEL_COM_YOUR_APP: DEBUG
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9090 || curl -f http://localhost:9090/actuator/health || nc -z localhost 9090 || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 90s  # Увеличиваем время на старт
    # Добавляем команду для логирования
    command: >
      sh -c "
      echo 'Starting stats-server...'
      java -jar /app/app.jar 2>&1 | tee /tmp/app.log
      "

#  ewm-service:
#    ports:
#      - "8080:8080"
#
#  ewm-db:
#    image: postgres:16.1
